### ISSUE TITLE
Reddit and So data crashes

### ISSUE THREAD

**Issue by RichardShea** [alexandersoen/unipoint#1]
When I run `!python3 train_real.py`, I get the following Traceback:

[Info] Number of parameters: 8768
Start Processing: reddit_expsum

[2022-09-13 22:15:34.833956] ----- Starting Epoch 1 -----
 17% 16/94 [00:13<01:06,  1.18it/s]
Traceback (most recent call last):
  File "train_real.py", line 89, in <module>
    validation_data=validation_dataset, patience=PATIENCE, save_model=save_path, from_checkpoint=True)
  File "/content/models/abstract_neural.py", line 125, in train_model
    loss = self.ll(batch)
  File "/content/models/basis_sum/abstract_sum.py", line 91, in ll
    sampler = Uniform(torch.zeros_like(mc_ts), mc_ts)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributions/uniform.py", line 56, in __init__
    raise ValueError("Uniform is not defined when low>= high")
ValueError: Uniform is not defined when low>= high

**My only workaround is to comment out the two datasets in the file and 'mooc' runs.**
```
#%%
real_data_list = [
    # 'reddit',
    'mooc',
    # 'so',
]
```

**Comment by alexandersoen** [comment]
Odd, I suspect something strange numerically is occurring as when checking `torch.any(torch.zeros_like(mc_ts) >= mc_ts)` I am only getting falses.

Nevertheless, I've just added a small constant which should resolve this issue.
